# typed: false
# frozen_string_literal: true

# This file was generated by Hyperterse. It is a bare minimum Homebrew formula.
# Documentation: https://docs.brew.sh/Formula-Cookbook
# This file is automatically updated by scripts/version.ts

class Hyperterse < Formula
  desc "A declarative interface to connect your database to your AI agents"
  homepage "https://hyperterse.com"
  version "2.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hyperterse/hyperterse/releases/download/v#{version}/hyperterse-darwin-amd64"
      sha256 "bef4c21242f75632090891975d2260f67d786eb0330eea0e84fa4800d3694605"
    elsif Hardware::CPU.arm?
      url "https://github.com/hyperterse/hyperterse/releases/download/v#{version}/hyperterse-darwin-arm64"
      sha256 "237e9aed3acb052cd9a47bbbed1450be8871c57f2a672894ae3231de3e8bc64b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hyperterse/hyperterse/releases/download/v#{version}/hyperterse-linux-amd64"
      sha256 "d6cdb4a3c66f21d33de773d1e33a821cc8007f9bbff095001886a77db8ea1583"
    elsif Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hyperterse/hyperterse/releases/download/v#{version}/hyperterse-linux-arm64"
        sha256 "c7decc8e984d1cee674651746f3a9475c1a5257ba33f25a10b53c47918fb9d13"
      else
        url "https://github.com/hyperterse/hyperterse/releases/download/v#{version}/hyperterse-linux-arm"
        sha256 "291eaee1c923528ee5d25b9b7c71453c19a49891f48ec093e07a673aa0ecfbb1"
      end
    end
  end

  def install
    # Homebrew downloads the binary file, rename it to 'hyperterse'
    binary = Dir["hyperterse-*"].first
    bin.install binary => "hyperterse"
  end

  test do
    system "#{bin}/hyperterse", "--version"
  end
end
