# typed: false
# frozen_string_literal: true

# This file was generated by Hyperterse. It is a bare minimum Homebrew formula.
# Documentation: https://docs.brew.sh/Formula-Cookbook
# This file is automatically updated by scripts/version.sh

class Hyperterse < Formula
  desc "A declarative interface to connect your database to your AI agents"
  homepage "https://hyperterse.com"
  version "1.0.0-beta.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hyperterse/hyperterse/releases/download/v#{version}/hyperterse-darwin-amd64"
      sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"
    elsif Hardware::CPU.arm?
      url "https://github.com/hyperterse/hyperterse/releases/download/v#{version}/hyperterse-darwin-arm64"
      sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hyperterse/hyperterse/releases/download/v#{version}/hyperterse-linux-amd64"
      sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"
    elsif Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hyperterse/hyperterse/releases/download/v#{version}/hyperterse-linux-arm64"
        sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"
      else
        url "https://github.com/hyperterse/hyperterse/releases/download/v#{version}/hyperterse-linux-arm"
        sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"
      end
    end
  end

  def install
    bin.install "hyperterse"
  end

  test do
    system "#{bin}/hyperterse", "--version"
  end
end
